In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
house = pd.read_csv("HouseVotes84.csv")
house.head()

Class   V1 V2 V3   V4   V5 V6 V7 V8 V9 V10  V11  V12 V13 V14 V15  V16
0  republican    n  y  n    y    y  y  n  n  n   y  NaN    y   y   y   n    y
1  republican    n  y  n    y    y  y  n  n  n   n    n    y   y   y   n  NaN
2    democrat  NaN  y  y  NaN    y  y  n  n  n   n    y    n   y   y   n    n
3    democrat    n  y  y    n  NaN  y  n  n  n   n    y    n   y   n   n    y
4    democrat    y  y  y    n    y  y  n  n  n   n    y  NaN   y   y   y    y

In [3]:
house.isnull().sum()

Class      0
V1        12
V2        48
V3        11
V4        11
V5        15
V6        11
V7        14
V8        15
V9        22
V10        7
V11       21
V12       31
V13       25
V14       17
V15       28
V16      104
dtype: int64

In [4]:
X = house.iloc[:,1:17]
X.head()

V1 V2 V3   V4   V5 V6 V7 V8 V9 V10  V11  V12 V13 V14 V15  V16
0    n  y  n    y    y  y  n  n  n   y  NaN    y   y   y   n    y
1    n  y  n    y    y  y  n  n  n   n    n    y   y   y   n  NaN
2  NaN  y  y  NaN    y  y  n  n  n   n    y    n   y   y   n    n
3    n  y  y    n  NaN  y  n  n  n   n    y    n   y   n   n    y
4    y  y  y    n    y  y  n  n  n   n    y  NaN   y   y   y    y

In [5]:
from sklearn_pandas import CategoricalImputer
imp = CategoricalImputer()
X = np.array(X)
X = imp.fit_transform(X)

#v7=np.array(hp['V7'])
#hp['V7']=imputer_categorical.fit_transform(v7)

In [6]:
X = pd.DataFrame(X)
X.head()

0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15
0  n  y  n  y  y  y  n  n  n  y  y  y  y  y  n  y
1  n  y  n  y  y  y  n  n  n  n  n  y  y  y  n  y
2  y  y  y  y  y  y  n  n  n  n  y  n  y  y  n  n
3  n  y  y  n  y  y  n  n  n  n  y  n  y  n  n  y
4  y  y  y  n  y  y  n  n  n  n  y  y  y  y  y  y

In [7]:
X = pd.get_dummies(X)
X.head()

0_n  0_y  1_n  1_y  2_n  2_y  3_n  3_y  4_n  4_y  ...  11_n  11_y  12_n  \
0    1    0    0    1    1    0    0    1    0    1  ...     0     1     0   
1    1    0    0    1    1    0    0    1    0    1  ...     0     1     0   
2    0    1    0    1    0    1    0    1    0    1  ...     1     0     0   
3    1    0    0    1    0    1    1    0    0    1  ...     1     0     0   
4    0    1    0    1    0    1    1    0    0    1  ...     0     1     0   

   12_y  13_n  13_y  14_n  14_y  15_n  15_y  
0     1     0     1     1     0     0     1  
1     1     0     1     1     0     0     1  
2     1     0     1     1     0     1     0  
3     1     1     0     1     0     0     1  
4     1     0     1     0     1     0     1  

[5 rows x 32 columns]

In [10]:
y = house[['Class']]
y.head()

Class
0  republican
1  republican
2    democrat
3    democrat
4    democrat

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.20,random_state=0)

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [16]:
classifier_knn = KNeighborsClassifier(n_neighbors=5) #Building Model
classifier_knn.fit(X_train, y_train) #Fitting Model

C:\Users\mayur\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [17]:
y_pred_knn = classifier_knn.predict(X_test) #Predicting data
y_pred_knn

array(['democrat', 'democrat', 'democrat', 'democrat', 'democrat',
       'democrat', 'democrat', 'republican', 'democrat', 'republican',
       'republican', 'democrat', 'democrat', 'republican', 'republican',
       'republican', 'democrat', 'democrat', 'democrat', 'republican',
       'democrat', 'democrat', 'republican', 'democrat', 'democrat',
       'democrat', 'republican', 'democrat', 'republican', 'democrat',
       'republican', 'democrat', 'democrat', 'democrat', 'republican',
       'democrat', 'republican', 'republican', 'democrat', 'democrat',
       'republican', 'democrat', 'democrat', 'republican', 'republican',
       'republican', 'democrat', 'democrat', 'republican', 'democrat',
       'republican', 'democrat', 'democrat', 'democrat', 'republican',
       'democrat', 'republican', 'democrat', 'democrat', 'republican',
       'democrat', 'democrat', 'republican', 'democrat', 'democrat',
       'republican', 'republican', 'democrat', 'republican', 'republican',
      

In [18]:
from sklearn.metrics import classification_report, confusion_matrix #Importing confusion matrix package
cm_knn = confusion_matrix(y_test, y_pred_knn) #Confusion Matrix
cm_knn

array([[48,  4],
       [ 3, 32]], dtype=int64)

In [19]:
from sklearn.metrics import accuracy_score #Importing accuracy score package
Accuracy_Score_knn = accuracy_score(y_test, y_pred_knn) #Calculating Accuracy Score
Accuracy_Score_knn

0.9195402298850575

In [20]:
# Importing Naive Bayes Algorithm
from sklearn.naive_bayes import GaussianNB

In [21]:
classifier_NB = GaussianNB() #Building Model
classifier_NB.fit(X_train,y_train) #Fitting Model

C:\Users\mayur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB(priors=None, var_smoothing=1e-09)

In [22]:
y_pred_NB = classifier_NB.predict(X_test) #Predicting data
y_pred_NB

array(['democrat', 'democrat', 'democrat', 'democrat', 'democrat',
       'democrat', 'democrat', 'republican', 'republican', 'republican',
       'republican', 'democrat', 'democrat', 'democrat', 'republican',
       'republican', 'republican', 'democrat', 'democrat', 'republican',
       'democrat', 'democrat', 'republican', 'democrat', 'democrat',
       'democrat', 'republican', 'democrat', 'republican', 'democrat',
       'republican', 'democrat', 'democrat', 'democrat', 'republican',
       'democrat', 'republican', 'democrat', 'democrat', 'democrat',
       'republican', 'democrat', 'democrat', 'democrat', 'republican',
       'republican', 'democrat', 'democrat', 'republican', 'democrat',
       'republican', 'democrat', 'democrat', 'democrat', 'republican',
       'democrat', 'republican', 'democrat', 'democrat', 'republican',
       'democrat', 'democrat', 'republican', 'democrat', 'democrat',
       'democrat', 'republican', 'democrat', 'republican', 'republican',
       're

In [23]:
cm_NB = confusion_matrix(y_test, y_pred_NB) #Confusion Matrix
cm_NB

array([[51,  1],
       [ 2, 33]], dtype=int64)

In [24]:
Accuracy_Score_NB = accuracy_score(y_test, y_pred_NB) #Calculating Accuracy Score
Accuracy_Score_NB

0.9655172413793104

In [25]:
# Importing Support Vector Machine Algorithm
from sklearn.svm import SVC
classifier_svm_linear = SVC(kernel = 'linear', random_state = 0) #Building Model
classifier_svm_linear.fit(X_train, y_train) #Fitting Model

C:\Users\mayur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='linear', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [26]:
y_pred_svm_linear = classifier_svm_linear.predict(X_test) #Predicting data
y_pred_svm_linear

array(['democrat', 'democrat', 'democrat', 'democrat', 'democrat',
       'democrat', 'democrat', 'republican', 'democrat', 'republican',
       'republican', 'democrat', 'democrat', 'democrat', 'republican',
       'republican', 'republican', 'democrat', 'democrat', 'republican',
       'democrat', 'democrat', 'republican', 'democrat', 'democrat',
       'democrat', 'republican', 'democrat', 'republican', 'democrat',
       'republican', 'democrat', 'democrat', 'democrat', 'republican',
       'democrat', 'republican', 'democrat', 'democrat', 'democrat',
       'republican', 'democrat', 'democrat', 'republican', 'republican',
       'republican', 'democrat', 'democrat', 'republican', 'democrat',
       'republican', 'democrat', 'democrat', 'democrat', 'republican',
       'democrat', 'republican', 'democrat', 'democrat', 'republican',
       'democrat', 'democrat', 'republican', 'democrat', 'democrat',
       'democrat', 'republican', 'democrat', 'republican', 'republican',
       're

In [27]:
cm_svm_linear = confusion_matrix(y_test, y_pred_svm_linear) #Confusion Matrix
cm_svm_linear

array([[51,  1],
       [ 2, 33]], dtype=int64)

In [28]:
Accuracy_Score_svm_linear = accuracy_score(y_test, y_pred_svm_linear) #Calculating Accuracy Score
Accuracy_Score_svm_linear

0.9655172413793104

In [29]:
classifier_svm_rbf = SVC(kernel = 'rbf', random_state = 0) #Building Model using 'rbf' = Gaussion
classifier_svm_rbf.fit(X_train, y_train) #Fitting Model

C:\Users\mayur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\mayur\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=0,
    shrinking=True, tol=0.001, verbose=False)

In [30]:
y_pred_svm_rbf = classifier_svm_rbf.predict(X_test) #Predicting data
y_pred_svm_rbf

cm_svm_rbf = confusion_matrix(y_test, y_pred_svm_linear) #Confusion Matrix
cm_svm_rbf

Accuracy_Score_svm_rbf = accuracy_score(y_test, y_pred_svm_rbf) #Calculating Accuracy Score
Accuracy_Score_svm_rbf

0.9770114942528736

In [31]:
classifier_svm_poly = SVC(kernel = 'poly', random_state = 0)#Building Model using 'poly' = Polynomial
classifier_svm_poly.fit(X_train, y_train) #Fiiting Model

y_pred_svm_poly = classifier_svm_poly.predict(X_test) #Predicting data
y_pred_svm_poly

cm_svm_poly = confusion_matrix(y_test, y_pred_svm_poly) #Confusion Matrix
cm_svm_poly

Accuracy_Score_svm_poly = accuracy_score(y_test, y_pred_svm_poly) #Calculating Accuracy Score
Accuracy_Score_svm_poly

C:\Users\mayur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\mayur\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9425287356321839

In [32]:
classifier_svm_sigmoid = SVC(kernel = 'sigmoid', random_state = 0)#Building Model using 'sigmoid' = Sigmoid
classifier_svm_sigmoid.fit(X_train, y_train) #Fitting Model

y_pred_svm_sigmoid = classifier_svm_sigmoid.predict(X_test) #Predicting data
y_pred_svm_sigmoid

cm_svm_sigmoid = confusion_matrix(y_test, y_pred_svm_sigmoid) #Confusion Matrix
cm_svm_sigmoid

Accuracy_Score_svm_sigmoid = accuracy_score(y_test, y_pred_svm_sigmoid) #Calculating Accuracy Score
Accuracy_Score_svm_sigmoid

C:\Users\mayur\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\mayur\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


0.9655172413793104

In [33]:
# Importing Decision Tree Algorithm
from sklearn.tree import DecisionTreeClassifier
classifier_dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0) #Building Model
classifier_dt.fit(X_train, y_train) #Fitting Model

y_pred_dt = classifier_dt.predict(X_test)
y_pred_dt

cm_dt = confusion_matrix(y_test, y_pred_dt) #Confussion Matrix
cm_dt

Accuracy_Score_dt = accuracy_score(y_test, y_pred_dt) #Calculating Accuracy Score
Accuracy_Score_dt

0.9425287356321839

In [34]:
# Importing Random Forest Algorithm
from sklearn.ensemble import RandomForestClassifier
classifier_rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0) #Building Model
classifier_rf.fit(X_train, y_train) #Fitting Model

y_pred_rf = classifier_rf.predict(X_test)
y_pred_rf

cm_rf = confusion_matrix(y_test, y_pred_rf)
cm_rf

Accuracy_Score_rf = accuracy_score(y_test, y_pred_rf)
Accuracy_Score_rf

C:\Users\mayur\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


0.9655172413793104

In [35]:
print("K-Nearest Neighbors =",Accuracy_Score_knn)
print("Naive Bayes =",Accuracy_Score_NB)
print("Support Vector Machine Linear =",Accuracy_Score_svm_linear)
print("Support Vector Machine Gaussion =",Accuracy_Score_svm_rbf)
print("Support Vector Machine Polynomial =",Accuracy_Score_svm_poly)
print("Support Vector Machine Sigmoid =",Accuracy_Score_svm_sigmoid)
print("Decision Tree =",Accuracy_Score_dt)
print("Random Forest =",Accuracy_Score_rf)

K-Nearest Neighbors = 0.9195402298850575
Naive Bayes = 0.9655172413793104
Support Vector Machine Linear = 0.9655172413793104
Support Vector Machine Gaussion = 0.9770114942528736
Support Vector Machine Polynomial = 0.9425287356321839
Support Vector Machine Sigmoid = 0.9655172413793104
Decision Tree = 0.9425287356321839
Random Forest = 0.9655172413793104
